name: Tests
"on":
    pull_request: {}
jobs:
    unit:
        name: Unit Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                go-version: "1.15"
            - uses: actions/cache@v2
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                path: ~/go/pkg/mod
                restore-keys: ${{ runner.os }}-go-
            - name: Install richgo
              run: go get -u github.com/kyoh86/richgo
            - name: Run Tests
              run: richgo test ./...
              env:
                RICHGO_FORCE_COLOR: "1"
