name: Test
"on":
    pull_request: {}
jobs:
    test:
        name: Test
        runs-on:
            - ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Go environment
              uses: actions/setup-go@v2
              with:
                go-version: "1.15"
            - name: Cache
              uses: actions/cache@v2
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                path: ~/go/pkg/mod
                restore-keys: ${{ runner.os }}-go-
            - name: Install richgo
              run: go get -u github.com/kyoh86/richgo
            - name: Test
              run: RICHGO_FORCE_COLOR=1 richgo test ./...
