name: Update Release
"on":
    push:
        branches:
            - main
jobs:
    update:
        name: Update Release
        runs-on:
            - ubuntu-latest
        steps:
            - name: Release Drafter
              uses: release-drafter/release-drafter@v5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
